// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brsvmzczilegueifvjxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyc3ZtemN6aWxlZ3VlaWZ2anh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTA4MDcsImV4cCI6MjA2NzEyNjgwN30.bRXsNg3CG-0DAJbiWbCbmRDXePjieCkDHD9jEoRduFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});